export const ErrorCodeEnum = {
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
    AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
    AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
    AUTH_FORBIDDEN_ACCESS: 'AUTH_FORBIDDEN_ACCESS',
    AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
    AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',

    ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',

    BAD_REQUEST: 'BAD_REQUEST',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    VALIDATION_FAILED: 'VALIDATION_FAILED',

    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
    WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
    MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',

    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
